env:
  es6: true
  node: true
extends: 'eslint:recommended'
rules:
  no-unused-vars:
    - warn
    - args: none
  no-console:
    - off
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always