swagger: '2.0'
info:
  title: SMV User Auth Service API
  description: Simple Visitor Management User Authentication Service API
  version: 0.0.3
schemes:
  - http
  - https
host: 'localhost:6002'
basePath: /api/smv/v1/auth
produces:
  - application/json
paths:
  /login:
    post:
      summary: 주어진 인증 정보로 로그인
      tags:
        - 사용자인증
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - name: email
          in: formData
          type: string
          required: true
          description: 사용자 Email
        - name: passwd
          in: formData
          required: true
          type: string
          description: 사용자 비밀번호
      responses:
        '200':
          description: 로그인 성공
          headers:
            'X-AUTH-TOKEN':
              description: Authentication Token
              type: string
          schema:
            $ref: '#/definitions/UserObject'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /logout:
    get:
      summary: 로그인 상태에서 로그아웃
      tags:
        - 사용자인증
      parameters:
        - name: X-AUTH-TOKEN
          description: 인증 토큰
          in: header
          type: string
          required: true
      responses:
        '200':
          description: 로그아웃 성공
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /userinfo:
    get:
      summary: 로그인한 사용자의 정보를 조회
      tags:
        - 사용자인증
      parameters:
        - name: X-AUTH-TOKEN
          description: 인증 토큰
          in: header
          type: string
          required: true
      responses:
        '200':
          description: 인증된 사용자 정보
          schema:
            $ref: '#/definitions/UserObject'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  UserObject:
    type: object
    properties:
      userid:
        type: string
        description: 사용자 ID
        example: CN=John Doe/OU=ACME/O=IBM
      serial:
        type: string
        description: 사용자 사번
        example: 1234567890
      name:
        type: string
        description: 사용자 성명
        example: John Doe
      phone:
        type: string
        description: 유선전화번호
        example: +82-2-1234-0000
      mobile:
        type: string
        description: 휴대전화번호
        example: +82-10-1234-0000
      email:
        type: string
        description: 이메일 연락처
        example: john.doe@acme.ibm.com
      role:
        type: string
        description: 사용자 역할 정보
        enum:
          - RECEPTION
          - ESCORT
          - ADMIN
  Error:
    type: object
    properties:
      error:
        type: string
        example: failed to get document
      reason:
        type: string
        example: insufficient parameter
      statusCode:
        type: integer
        format: int32
        example: 500